---
services:
  api:
    build:
      context: api
      dockerfile: ../Dockerfile.go.dev
    container_name: api
    working_dir: /app
    expose:
      - 8080
    ports:
      - 8080:8080
    command: ["go", "run", "main.go"]
    environment:
      - DB_HOST=db
      - HOST=0.0.0.0
    depends_on:
      - db
    volumes:
      - ./api:/app
    networks:
      - front-end
      - back-end

  # Fetcher service
  fetcher:
    build:
      context: fetcher
      dockerfile: ../Dockerfile.go.dev
    container_name: fetcher
    working_dir: /app
    command: ["go", "run", "main.go"]
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./fetcher:/app
    networks:
      - back-end

  # Processors service
  processors:
    build:
      context: processors
      dockerfile: ../Dockerfile.go.dev
    container_name: processors
    working_dir: /app
    command: ["go", "run", "main.go"]
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - ./processors:/app
    networks:
      - back-end

  # Web Service
  web:
    build:
      context: web
      dockerfile: ../Dockerfile.nodejs.dev
    container_name: web
    working_dir: /app
    command: ["npm", "run", "dev"]
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - VITE_API_DOMAIN=http://localhost:8080
      - VITE_WS_DOMAIN=http://localhost:8081
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /pnpm-store
      - /app/node_modules
    networks:
      - front-end

  # Database Service
  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/events.sql
    networks:
      - back-end

  # Redis Service
  redis:
    image: redis:8.0.1-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - back-end

networks:
  front-end:
    driver: bridge
  back-end:

volumes:
  pgdata:
